name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest

    # Steps to setup the environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash && source "${HOME}/google-cloud-sdk/path.bash.inc" && gcloud components update

      - name: Authenticate via Service Account Key
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS | base64 --decode > creds.json 
          gcloud auth activate-service-account --key-file creds.json
          gcloud config set project appointmentbot-413314
          gcloud config set compute/region europe-west10
          echo "don't do this at home, kids"
          gcloud auth configure-docker


      - name: Build and Publish Docker Images
        run: |
          docker build -t appointment .
          docker tag appointment europe-west10-docker.pkg.dev/appointmentbot-413314/appointment-bot/appointment
          docker push appointment europe-west10-docker.pkg.dev/appointmentbot-413314/appointment-bot/appointment
