name: Build and Push Docker Image

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest

    # Steps to setup the environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246770851643:role/einbuergerungs-appointments-github-actions
          aws-region: eu-central-1

      - name: Build and Publish Docker Images
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin "246770851643.dkr.ecr.eu-central-1.amazonaws.com"
          docker build -t appointment .
          docker tag appointment "246770851643.dkr.ecr.eu-central-1.amazonaws.com/appointment-bot:latest"
          docker push "246770851643.dkr.ecr.eu-central-1.amazonaws.com/appointment-bot:latest"
